# create pr with bumpped version, if merged auto-release
name: Release-routine
on:
  workflow_dispatch:
  schedule:
      - cron: "0 10 * * 1"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  pull-requests: write
  contents: write

jobs:
  release:
    if: ${{ !startsWith(github.head_ref, 'changeset') && !startsWith(github.head_ref, 'release') }}
    name: Release-routine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Setup Node.js 16
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node16
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install

      - id: get_date
        run: echo "DATE=$(date +"%Y-%m-%d")" >> $GITHUB_OUTPUT

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: npx changeset version
          title: release-routine-${{ steps.get_date.outputs.DATE }}
          commit: 'release: ${{ steps.get_date.outputs.DATE }}-auto-generated-by-ci'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
