# run when pr from changeset/main is merged to main
name: Release
on:
  pull_request:
    branches:
      - main
    paths:
      - '**/CHANGELOG.md'
    types:
      - closed
   

jobs:
  if_release_routine_merged:
    if: ${{ github.event.pull_request.merged == true && (startsWith(github.head_ref, 'changeset') || startsWith(github.head_ref, 'release')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Note branch
        run: |
          echo "::notice ::The PR from ${{ github.head_ref }} was merged into main, run the publish pipeline"

      - name: Checkout Repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node16
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Get Date
        id: get_date
        run: echo "DATE=$(date +"%Y-%m-%d")" >> $GITHUB_OUTPUT

      - name: Install And Publish
        id: install_and_publish
        run: |
          pnpm install
          pnpm run publish
          node ./scripts/pushCurrentVersionTag.js
          pnpm run pack
        env:
          VSCE_PAT: ${{ secrets.AZURE_TOKEN }}

      - name: Create Github Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: ./*.vsix
          body_path: CHANGELOG.md
          target_commitish: ${{ github.sha }}
          tag_name: ${{ steps.install_and_publish.outputs.tag }}
