# run when pr from changeset/main is merged to main
name: Release
on:
  pull_request:
    branches:
      - main
    paths:
      - '**/CHANGELOG.md'
    types:
      - closed

jobs:
  if_release_routine_merged:
    if: ${{ github.event.pull_request.merged == true && (startsWith(github.head_ref, 'changeset') || startsWith(github.head_ref, 'release')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Note branch
        run: |
          echo "::notice ::The PR from ${{ github.head_ref }} was merged into main, run the publish pipeline"

      - name: Checkout Repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node16
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Get Date
        id: get_date
        run: echo "DATE=$(date +"%Y-%m-%d")" >> $GITHUB_OUTPUT

      - name: Install And Publish
        run: |
          pnpm install
          pnpm run publish
          node ./scripts/pushCurrentVersionTag.js
        env:
          VSCE_PAT: ${{ secrets.AZURE_TOKEN }}

      - name: Create Github Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: ./*.vsix
          body_path: CHANGELOG.md
          target_commitish: ${{ github.sha }}
